export const userInputToList = {
  id: true,
  email: true,
  profileName: true,
  userName: true,
  firstName: true,
  surname: true,
  fullName: true,
  password: true,
  phoneNumber: true,
  active: true,
  status: true,
  userBirth: true,
  banned: true,
  createdAt: true,
  updatedAt: true,
  urlProfile: true,
  role: true,
};
